package com.example.onlinestore.UserManagment.Buyer;

import com.sun.istack.NotNull;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.validation.Valid;

@Controller // This means that this class is a Controller
@RequestMapping(path="/buyer") // This means URL's start with /demo (after Application path)
public class BuyerResource {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BuyerRepository BuyerRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Buyer> getAllUsers() {
        // This returns a JSON or XML with the users
        return BuyerRepository.findAll();
    }
}
